name: main

on:
    push:
        branches:
            - main

env:
    NODE_VERSION: 18.17

jobs:
    main:
        name: Main
        runs-on: ubuntu-latest
        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm ci

            - name: Code Linting
              run: npm run lint

            - name: Code Testing & publish code coverage
              uses: paambaati/codeclimate-action@v5.0.0
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              with:
                  coverageCommand: npm run test-coverage
                  coverageLocations: ${{ github.workspace }}/coverage/*.xml:clover
                  debug: true
